CREATE TABLE `servicio` (
  `idServicio` int(11) NOT NULL AUTO_INCREMENT,
  `cliente` int(11) DEFAULT NULL,
  `nombre` varchar(50) DEFAULT NULL,
  `a_paterno` varchar(50) DEFAULT NULL,
  `a_materno` varchar(45) DEFAULT NULL,
  `fecha_nacimiento` date DEFAULT NULL,
  `idPaisNacimiento` int(11) DEFAULT NULL,
  `idEstadoNacimiento` int(11) DEFAULT NULL,
  `idCiudadNacimiento` int(11) DEFAULT NULL,
  `calle1` varchar(100) DEFAULT NULL,
  `calle2` varchar(45) DEFAULT NULL,
  `noExt` varchar(5) DEFAULT NULL,
  `noInt` varchar(5) DEFAULT NULL,
  `codigoPostal` int(11) DEFAULT NULL,
  `idColonia` int(11) DEFAULT NULL,
  `idCiudad` int(11) DEFAULT NULL,
  `idEstado` int(11) DEFAULT NULL,
  `idPais` int(11) DEFAULT NULL,
  `referenciaDireccion` text DEFAULT NULL,
  `idSexo` int(11) DEFAULT NULL,
  `idComplexion` int(11) DEFAULT NULL,
  `peso` decimal(10,2) DEFAULT NULL,
  `estatura` double(10,2) DEFAULT NULL,
  `idEstadoCivil` int(11) DEFAULT NULL,
  `telefono` varchar(10) DEFAULT NULL,
  `idTipoTelefono` int(11) DEFAULT NULL,
  `correoElectronico` varchar(120) DEFAULT NULL,
  `idParentesco` int(11) DEFAULT NULL,
  `nombreMedico` varchar(50) DEFAULT NULL,
  `especialidadMedico` varchar(50) DEFAULT NULL,
  `telefonoMedico` varchar(10) DEFAULT NULL,
  `correoElectronicoMedico` varchar(120) DEFAULT NULL,
  `enfermedades` text DEFAULT NULL,
  `procedimientos` text DEFAULT NULL,
  `medicamentos` text DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `tieneCovid` bit(1) DEFAULT NULL,
  `tieneAlzheimer` bit(1) DEFAULT NULL,
  `movimiento` bit(1) DEFAULT NULL,
  `idTipoServicio` int(11) DEFAULT NULL,
  `idResponsable` int(11) DEFAULT NULL,
  `precioServicio` decimal(10,2) DEFAULT NULL,
  `cantidadPagada` decimal(10,2) DEFAULT NULL,
  `cantidadPorPagar` decimal(10,2) DEFAULT NULL,
  `colabReq` int(11) DEFAULT NULL,
  `estatus` varchar(45) DEFAULT NULL,
  `fechaCreacion` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`idServicio`),
  KEY `servicio_sexo_idx` (`idSexo`),
  KEY `servicio_esciv_idx` (`idEstadoCivil`),
  KEY `servicio_pais_idx` (`idPais`),
  KEY `servicio_estado_idx` (`idEstado`),
  KEY `servicio_ciudad_idx` (`idCiudad`),
  KEY `servicio_colonia_idx` (`idColonia`),
  CONSTRAINT `servicio_ciudad` FOREIGN KEY (`idCiudad`) REFERENCES `ciudad` (`idCiudad`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `servicio_colonia` FOREIGN KEY (`idColonia`) REFERENCES `colonia` (`idColonia`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `servicio_esciv` FOREIGN KEY (`idEstadoCivil`) REFERENCES `estadocivilcat` (`idEstadoCivil`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `servicio_estado` FOREIGN KEY (`idEstado`) REFERENCES `estado` (`idEstado`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `servicio_pais` FOREIGN KEY (`idPais`) REFERENCES `pais` (`idPais`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `servicio_sexo` FOREIGN KEY (`idSexo`) REFERENCES `sexocat` (`idSexo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;